library(plyr)

dados.quantidade.questoes.submetidas = read.csv("../Dados/exercicios-20112.csv")
print("Colunas da Base:")
print(colnames(dados.quantidade.questoes.submetidas))
print("")
print(paste("Tamanho da Base em Linhas:", nrow(dados.quantidade.questoes.submetidas)))
print(paste("Quantidade de Alunos que Submeteram Exercicios:", length(unique(dados.quantidade.questoes.submetidas$matricula))))

dados.quantidade.questoes.submetidas = dados.quantidade.questoes.submetidas[dados.quantidade.questoes.submetidas$nota == 10.0, ]
print("")
print("")
print("")
print("Filtrando a Base para Considerar apenas os Exercicios Submetidos Corretamente")
print("")
print("")
print("")
print(paste("Tamanho da Base em Linhas:", nrow(dados.quantidade.questoes.submetidas)))
print(paste("Quantidade de Alunos que Submeteram Exercicios:", length(unique(dados.quantidade.questoes.submetidas$matricula))))

print("")
print("")
print("")
print("Filtrando a Base para Considerar apenas os Exercicios Submetidos Antes da Primeira Prova: ")
print("")
print("")
print("")

dados.questoes.submetidas = read.csv("../Dados/exercicios-20112.csv")
print("Questoes Submetidas")
print("")
print("")
print("")
print("Colunas da Base:")
print(colnames(dados.questoes.submetidas))
print(paste("Tamanho da Base em Linhas:", nrow(dados.questoes.submetidas)))
print(paste("Quantidade de Questoes Submetidas Corretamente:", length(unique(dados.questoes.submetidas$questao))))
print("")
print("Filtrando a Base para Considerar apenas os Exercicios Submetidos Corretamente")
print("")
print("")
print("")
dados.questoes.submetidas = dados.questoes.submetidas[dados.questoes.submetidas$nota == 10.0, ]
print(paste("Tamanho da Base em Linhas:", nrow(dados.questoes.submetidas)))
print(paste("Quantidade de Questoes Submetidas Corretamente:", length(unique(dados.questoes.submetidas$questao))))
#dados.questoes.submetidas.histogram = data.frame(questao=unique(dados.questoes.submetidas), qtd=tapply(dados.questoes.submetidas$questao, dados.questoes.submetidas$questao, length))
#print(dados.questoes.submetidas.histogram)

#dados.questoes.submetidas.histogram = ddply(dados.questoes.submetidas, .(questao), nrow)
#colnames(dados.questoes.submetidas.histogram) = c("questao", "qtd")
#print(dados.questoes.submetidas.histogram)

#print(sort(dados.questoes.submetidas[, "questao"]))
png("Histograma - Questao x Quantidade.png", width=720, height=720)
hist(dados.questoes.submetidas[, "questao"])
#plot(dados.questoes.submetidas.histogram$questao, dados.questoes.submetidas.histogram$qtd)
dev.off()